# Project-wide Gradle settings.
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
ksp.incremental=true
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.configuration-cache=true
kotlin.code.style=official
